name: Build and Run Sonar

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Run Gradle build with Sonar
      run: ./gradlew build sonar --info
